
#cmd: column
#xpath: ./Production/Date/DateBegin
#---
#cmd: column
#xpath: ./Production/Date/DateEnd
#---
#cmd: column
#xpath: ./Production/Date/Accuracy
#---
cmd: column
xpath: ./Production/SummaryText
---
cmd: column
xpath: ./Identification/Title
title: Title
---
cmd: column
xpath: ./Identification/BriefDescription
title: Brief Description
---
cmd: if
xpath: ./Production/Date/DateBegin
title: ifdate