
cmd: column
xpath: ./Identification/Title
title: Title
---
cmd: column
xpath: ./Identification/BriefDescription
title: Brief Description
width: 50
---
cmd: column
xpath: ./Production/SummaryText
---
cmd: column
xpath: ./Production/Date
title: Production Date
#---
#cmd: ifelt
#xpath: ./Production/Date/DateEnd
#title: ifdate
---
cmd: column
xpath: ./Production/Date/Accuracy
---
cmd: column
xpath: ./Production/Date/DateBegin
title: Production DateBegin
---
cmd: column
xpath: ./Production/Date/DateEnd
title: Production DateEnd
---
cmd: column
xpath: ./References/Reference[@elementtype="First Published In"]/Date
title: First Pub In Date
