
#cmd: column
#xpath: ./Production/Date/DateBegin
#---
#cmd: column
#xpath: ./Production/Date/DateEnd
#---
#cmd: column
#xpath: ./Production/Date/Accuracy
#---
cmd: column
xpath: ./Identification/Title
title: Title
---
cmd: column
xpath: ./Identification/BriefDescription
title: Brief Description
---
cmd: column
xpath: ./Production/SummaryText
---
#cmd: if
#xpath: ./Production/Date
#---
#cmd: ifelt
#xpath: ./Production/Date/DateEnd
#title: ifdate
#---
cmd: column
xpath: ./Acquisition/Person/PersonName