"""
    Create a CSV file with the accession numbers of items on the website.

    Read the XML file downloaded from the website using the tools/export
    function, having selected either "Collection Items" or "Media".

    In the first case the file was downloaded to:
       HRM_Downloads/collection/collection_items/heathrobinsonmuseum.WordPress.yyyy-mm-dd.csv
    In the second case the file was downloaded to:
       HRM_Downloads/collection/media_items/heathrobinsonmuseum.WordPress.yyyy-mm-dd.csv
    The filename is the default generated by WordPress.

    Output to hrm/results/collection/collection_items/wordpress.yyyy-mm-dd.csv
    or to hrm/results/collection/media_items/wordpress.yyyy-mm-dd.csv
    Output is the sorted list of accession numbers of collection items and
    corresponding images in the collection.

    These should be identical.

    Note the filename appears in several elements of the input XML file.
    However, some of them are not complete or are otherwise not correct. The
    "<guid>" element seems to be the most reliable.

"""
import os
import re
import sys

from utl.normalize import normalize_id, denormalize_id

DOWNLOAD_DIR = '/Users/mlg/Cloud/hrm_downloads/collection'
COLLECTION_SUBDIR = 'collection_items'
MEDIA_SUBDIR = 'media_items'
RESULTS_DIR = '/Users/mlg/pyprj/hrm/results/collection'
DOWNLOADPREFIX = 'heathrobinsonmuseum.WordPress.'
RESULTSPREFIX = 'wordpress.'
FILENAMEPAT = r'heathrobinsonmuseum\.WordPress\.(\d{4}-\d\d-\d\d).xml'


def get_files(subdir):
    downloaddir = os.path.join(DOWNLOAD_DIR, subdir)
    resultsdir = os.path.join(RESULTS_DIR, subdir)
    newest_downloaded = ''
    for filename in os.listdir(downloaddir):
        if m := re.match(FILENAMEPAT, filename):
            candidate_date = m.group(1)
            if candidate_date > newest_downloaded:
                newest_downloaded = candidate_date
    if newest_downloaded:
        download_path = os.path.join(downloaddir, DOWNLOADPREFIX
                                     + newest_downloaded + '.xml')
        infile = open(download_path)
        print(f'{infile.name=}')
        results_path = os.path.join(resultsdir, RESULTSPREFIX
                                    + newest_downloaded + '.csv')
        outfile = open(results_path, 'w')
        print(f'{outfile.name=}')
        return infile, outfile
    else:
        print('No match for filename pattern')
        sys.exit()


def collection_subdir(subdir):
    infile, outfile = get_files(subdir)
    accns = set()
    nline = 0
    for line in infile:
        if '[CDATA[serial_no]]' in line:
            sline = next(infile)
            m = re.search(r'CDATA\[(.*)\]\]', sline)
            if not m:
                print(sline, 'fails pattern match')
                continue
            try:
                naccn = normalize_id(m.group(1))
            except (ValueError, AssertionError) as err:
                print(f'Line {nline}:', str(err))
                continue
            if naccn in accns:
                print(f'Duplicate: {m.group(1)}')
            accns.add(naccn)
    for naccn in sorted(accns):
        print(denormalize_id(naccn), file=outfile)
    print(f'{len(accns)} accession numbers in {subdir}')
    infile.close()
    outfile.close()


def media_subdir(subdir):
    infile, outfile = get_files(subdir)
    accns = {}
    nline = 0
    for line in infile:
        nline += 1
        if '[CDATA[_wp_attached_file]]' in line:
            sline = next(infile)
            m = re.search(r'CDATA\[(.*)\]\]', sline)
            if m:
                filename = m[1]
            else:
                print(sline, 'fails pattern match')
                continue
            if 'collection_' not in filename:
                continue
            m = re.match(r'collection_([^-]*)(-.*)?\.((jpeg)|(jpg))', filename)
            if not m:
                print(f'Match failed on {filename}')
                continue
            accn = m[1]
            subnum = m[2]
            # suffix = m[3]
            if subnum and len(subnum) > 1:  # if '-' followed by number and possibly A|B
                m = re.match(r'-(\d+)(A|B)?', subnum)
                if m:
                    subnum = m[1]
                    accn += '.' + subnum
                else:
                    print('nomatch', subnum, 'filename:', filename)
            try:
                naccn = normalize_id(accn)
            except (ValueError, AssertionError) as err:
                print(f'Line {nline}:', str(err))
                continue
            if naccn not in accns:
                accns[naccn] = filename
    for accnkey in sorted(accns):
        print(f'{denormalize_id(accnkey)},{accns[accnkey]}', file=outfile)
    print(f'{len(accns)} files in {subdir}')
    infile.close()
    outfile.close()


def main():
    collection_subdir(COLLECTION_SUBDIR)
    media_subdir(MEDIA_SUBDIR)


if __name__ == '__main__':
    assert sys.version_info >= (3, 11)
    if len(sys.argv) > 1:
        print('No parameters allowed. All values are hard-coded.')
        print('No action taken.')
        sys.exit(-1)
    main()
